# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0002_auto_20210117_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='podopieczny',
            name='sex',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='podopieczny',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
