# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0003_auto_20210117_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='podopieczny',
            name='cel',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='podopieczny',
            name='rodzaj_treningu',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='podopieczny',
            name='waga',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='podopieczny',
            name='wzrost',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='podopieczny',
            name='name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='podopieczny',
            name='sex',
            field=models.CharField(choices=[('Mężczyzna', 'Mężczyzna'), ('Kobieta', 'Kobieta')], default='', max_length=64),
        ),
    ]
