# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-18 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0004_auto_20210117_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='podopieczny',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to='plany/'),
        ),
        migrations.AlterField(
            model_name='podopieczny',
            name='rodzaj_treningu',
            field=models.TextField(default=''),
        ),
    ]
