# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-18 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0005_auto_20210118_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podopieczny',
            options={'ordering': ['imie_nazwisko']},
        ),
        migrations.RenameField(
            model_name='podopieczny',
            old_name='name',
            new_name='imie_nazwisko',
        ),
    ]
