# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-18 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0006_auto_20210118_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podopieczny',
            options={'ordering': ['imię_i_nazwisko']},
        ),
        migrations.RenameField(
            model_name='podopieczny',
            old_name='imie_nazwisko',
            new_name='imię_i_nazwisko',
        ),
        migrations.RenameField(
            model_name='podopieczny',
            old_name='sex',
            new_name='płeć',
        ),
    ]
