# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-18 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0007_auto_20210118_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podopieczny',
            old_name='description',
            new_name='opis',
        ),
    ]
