# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-18 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0008_auto_20210118_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='podopieczny',
            name='email',
            field=models.EmailField(default='', max_length=64, unique=True),
        ),
    ]
