# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podopieczni', '0009_podopieczny_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podopieczny',
            name='plan',
            field=models.FileField(upload_to='plany/'),
        ),
    ]
