# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-17 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to='plany/'),
        ),
    ]
